// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5fNiMUzzgZQ8MbYw9Gwe4w9mQVk9EAY',
    appId: '1:110964228514:web:49c15397450e6ae73972fb',
    messagingSenderId: '110964228514',
    projectId: 'instaclone-16d23',
    authDomain: 'instaclone-16d23.firebaseapp.com',
    storageBucket: 'instaclone-16d23.appspot.com',
    measurementId: 'G-KMV639D1RS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCylEy3OCniag6lbXzddvByhZx0q3XJWI',
    appId: '1:110964228514:android:89b83f8e015108163972fb',
    messagingSenderId: '110964228514',
    projectId: 'instaclone-16d23',
    storageBucket: 'instaclone-16d23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxFqDn4lshjF4JpkggmBCr5Gcz3wfsDog',
    appId: '1:110964228514:ios:078c1e99312bc4f73972fb',
    messagingSenderId: '110964228514',
    projectId: 'instaclone-16d23',
    storageBucket: 'instaclone-16d23.appspot.com',
    iosClientId: '110964228514-7d910vj7gv93bq6ctl5gh3siiom6vq3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxFqDn4lshjF4JpkggmBCr5Gcz3wfsDog',
    appId: '1:110964228514:ios:078c1e99312bc4f73972fb',
    messagingSenderId: '110964228514',
    projectId: 'instaclone-16d23',
    storageBucket: 'instaclone-16d23.appspot.com',
    iosClientId: '110964228514-7d910vj7gv93bq6ctl5gh3siiom6vq3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationInsta',
  );
}
